fix: correctly capitalize Control class in control.py
Received this error when running the code:
```
Traceback (most recent call last):
  File "Team-C/software/main.py", line 38, in <module>
    start()
  File "Team-C/software/main.py", line 26, in start
    controls = control.Control(comm)
AttributeError: module 'control' has no attribute 'Control'
```

`main.py` was referencing the `Control` class, which didn't exist
because the `c` wasn't capitalized. Correctly capitalizing the name
allows the class to be used.

Signed-off-by: Lucas Sta Maria <lucas.stamaria@gmail.com>